#!/bin/bash

if [ ${#} -lt 1 ]; then
	echo "PLEASE SPECIFY AN AWS BUCKET NAME AS AN ARGUMENT"
	exit 1
fi

while [ true ]; do
	clear
	echo "WAITING FOR FILE CHANGES... (Press CTRL+C to quit)"
	echo
	inotifywait -rq .
	echo
	echo "SYNCING WITH AWS..."
	echo
	aws s3 sync . s3://${1}/
	sleep 1
done
